import "../styles/globals.css";
import Head from "next/head";
import NavBar from "../components/NavBar";
import UserProvider from "../context/user";
// import UserProvider from "../context/user_old";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <UserProvider>
        <Head>
          <title>Inner Strength Yogi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <Component {...pageProps} />
      </UserProvider>
    </>
  );
}

export default MyApp;
